name: Tests

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  schedule:
    # Runs every day at 8 AM
    - cron: '0 8 * * *'

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [Ubuntu-latest, windows-latest ]
        # python-version: [ '3.7', '3.8', '3.9', '3.10'] 
        os: [Ubuntu-latest]
        python-version: [ '3.7'] 
      fail-fast: true
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox==3.24.3 tox-gh-actions==2.11.0
        pip install -r requirements_dev.txt

    - name: Copy pre-fetched data to running dir /tmp/alz_mri_cnn/ and echo
      run: |
        ls -las /tmp/alz_mri_cnn/
        cp -r pre_fetched_data/* /tmp/alz_mri_cnn/
    - name: post copy
      run: |
        echo COPY
        ls -las /tmp/alz_mri_cnn/

    - name: Test with tox
      run: tox
