name: Tests

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  - push
  - pull_request

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Ubuntu-latest, windows-latest ]
        python-version: [ '3.7', '3.8', '3.9', '3.10'] 
      fail-fast: true
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox==3.24.3 tox-gh-actions==2.11.0
        pip install -r requirements_dev.txt
    - name: Create kaggle.json
      env: 
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}  
      run: ./create_kaggle_json.sh env.KAGGLE_USERNAME, env.KAGGLE_PASSWORD
    - name: Make script executable
      run: chmod +x create_kaggle_json.sh
    - name: Test with tox
      run: tox
      env: 
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}