name: Tests

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  schedule:
    # Runs every day at 8 AM
    - cron: '0 8 */2 * *'

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Ubuntu-latest]
        python-version: [ '3.7']
      fail-fast: true
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox==3.24.3 tox-gh-actions==2.11.0
        pip install -r requirements_dev.txt
        chmod +x start_front_end.sh

    - name: Test with tox
      run: tox
